---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.3
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.3
    prometheus:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.42.100-192.168.42.250