---
- name: Configuring the nodes to use legacy iptables for compatibility with Kubernetes
  alternatives:
      name: "{{ item }}"
      path: /usr/sbin/{{ item }}-legacy
  with_items:
      - "iptables"
      - "ip6tables"
      - "ebtables"
  ignore_errors: true

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true