---
- name: Set up remote syslog server (promtail/loki)
  template:
    src: 50-promtail.conf.j2
    dest: /etc/rsyslog.d/50-promtail.conf
  when: remote_syslog.enabled is defined and remote_syslog.enabled == true

- name: Restart rsyslog service
  systemd:
    name: rsyslog
    enabled: true
    state: restarted
  when: remote_syslog.enabled is defined and remote_syslog.enabled == true

- name: Enable rsyslog service and assure it is started
  systemd:
    name: rsyslog
    enabled: true
    state: started
  when: remote_syslog.enabled is defined and remote_syslog.enabled == true

- name: Add Timesyncd Configuration
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf

- name: Restart systemd-timesyncd service
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: restarted

- name: Enable systemd-timesyncd service and assure it is started
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Set Timezone
  timezone:
    name: "{{ timezone | default('Europe/Amsterdam') }}"

- name: Add the RBD Module
  modprobe:
    name: rbd
    state: present

- name: Disable SWAP
  shell: |
    swapoff -a

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
