---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: openebs
  helmVersion: v3
  chart:
    repository: https://openebs.github.io/charts
    name: openebs
    version: 0.8.2
  values:
    rbac:
      pspEnabled: true
    ndm:
      sparse:
        count: '1'
    apiserver:
      sparse:
        enabled: true
