---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: openebs
  helmVersion: v3
  chart:
    git: git@github.com:openebs/charts.git
    path: stable/openebs
    ref: master

