---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: openebs
  helmVersion: v3
  chart:
    git: https://github.com/openebs/charts.git
    path: stable/openebs
    ref: master
  values:
    image:
      repository: ''
    rbac:
      pspEnabled: true
    ndm:
      image: 'quay.io/openebs/node-disk-manager'
      sparse:
        count: '1'
    ndmOperator:
      image: 'quay.io/openebs/node-disk-operator'
    webhook:
      image: 'quay.io/openebs/admission-server'
      imageTag: 1.9.0
    apiserver:
      image: 'quay.io/openebs/m-apiserver'
      imageTag: 1.9.0
      sparse:
        enabled: true
    localprovisioner:
      image: 'quay.io/openebs/provisioner-localpv'
      imageTag: 1.9.0
    snapshotOperator:
      controller:
        image: 'quay.io/openebs/snapshot-controller'
        imageTag: 1.9.0
      provisioner:
        image: 'quay.io/openebs/snapshot-provisioner'
        imageTag: 1.9.0
    provisioner:
      image: 'quay.io/openebs/openebs-k8s-provisioner'
      imageTag: 1.9.0
    helper:
      image: 'quay.io/openebs/linux-utils'
      imageTag: 1.9.0
    cstor:
      pool:
        image: 'raspbernetes/cstor-pool'
        imageTag: 1.9.0
      poolMgmt:
        image: 'raspbernetes/cstor-pool-mgmt'
        imageTag: 1.9.0
      target:
        image: 'quay.io/openebs/cstor-istgt'
        imageTag: 1.9.0
      volumeMgmt:
        image: 'quay.io/openebs/cstor-volume-mgmt'
        imageTag: 1.9.0
    policies:
      monitoring:
        image: 'quay.io/openebs/m-exporter'
        imageTag: 1.9.0
