---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: openebs
  helmVersion: v3
  chart:
    repository: https://openebs.github.io/charts
    name: openebs
    version: 0.8.2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-standard
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "3"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G

