createCRD: false
#git:
#  ssh:
#    secretName: flux-git-deploy
helm:
  versions: "v3"
#prometheus:
#  enabled: true
#  serviceMonitor:
#    create: true
#    namespace: flux
#    interval: 30s
#    scrapeTimeout: 10s
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 2Gi
