---
- hosts: k3s_storage
  become: true
  gather_facts: true

  # https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md
  tasks:
    - name: "Delete /var/lib/rook"
      command: rm -rf /var/lib/rook
  
    - name: "Zap the drives"
      command: # sgdisk --zap-all /dev/nvme0n1

    - name: Remove LVM partitions
      shell: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ls /dev/mapper/ceph--* | xargs -I% -- fuser --kill %
        - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup clear %
        - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup remove -f %
        - ls /dev/mapper/ceph--* | xargs -I% -- rm -rf %

    - name: "Wipe the block device"
      command: wipefs -af /dev/nvme0n1
    
    - name: Rebooting hosts
      reboot:
        msg: "Systems are being rebooted"
        reboot_timeout: 60
      ignore_errors: true
