---

- name: Create flux namespace
  command: "kubectl apply -f {{ REPO_ROOT }}/deployments/flux/_namespace.yaml"
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"

- name: Deploy Flux
  shell: |
    fluxctl install --git-user={{ github.username }} \
    --git-email={{ github.username }}@users.noreply.github.com \
    --git-url=git@github.com:{{ github.username }}/{{ github.repository_name }} \
    --git-branch={{ github.branch }} \
    --git-path=cluster \
    --namespace flux | kubectl apply -f -
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"

- name: Get Flux identity
  command: "{{ item }}"
  with_items:
    - fluxctl identity
  register: flux_identity
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"
    FLUX_FORWARD_NAMESPACE: flux
  until: "'ssh-rsa' in flux_identity.stdout"
  retries: 30
  delay: 10

- name: Register Flux Identity with GitHub
  script: "{{ REPO_ROOT }}/hack/add-repo-key.sh {{ github.username }} '{{ flux_identity.results[0].stdout }}' {{ github.repository_name }}"
  register: register_result
